# -*- coding: utf-8 -*-
"""pythonDay12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ig12n2-nrmnVNdWcwpOkREXxuB6ff3o8
"""

'''Write a program that will find factors of
the given number and find whether the factor is even or odd.Hint:Use Loop with if-else statement'''
find = int(input ("give a number to find a even or odd: "))
for good in range (1, find + 1):
  if find % good == 0:
    if good % 2 == 0:
      print(f"the given number{good} is even")
    else:
      print(f"the given number {good} is odd")

'''Write a code that accepts a sequence of words as input and prints the words in a
 sequence after sorting them alphabetically '''

input_string = input("Enter a sequence of words separated by spaces: ")
words = input_string.split()
words.sort()
print("Sorted words:")
for word in words:
    print(word)

# List to store numbers where all digits are even
even_digit_numbers = []

# Loop through numbers from 1000 to 3000 (both included)
for num in range(1000, 3001):
    num_str = str(num)  # Convert number to string to check each digit
    # Check if all digits are even
    if all(int(digit) % 2 == 0 for digit in num_str):
        even_digit_numbers.append(num_str)

# Print the numbers joined by commas on a single line
print(",".join(even_digit_numbers))

letters = 0
digits = 0
for char in sentence:
    if char.isalpha():
        letters += 1
    elif char.isdigit():
        digits += 1


print(f"LETTERS:{letters}")
print(f"DIGITS:{digits}")

num = input("Enter a number: ")

if num == num[::-1]:
    print("The number is a Palindrome.")
else:
    print("The number is NOT a Palindrome.")

