# -*- coding: utf-8 -*-
"""casestudy1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvHTLpQC2VP5isOWNgruRUvVsJwZp8_a
"""

import pandas as pd

# Assuming a dataframe 'movies' with columns: 'story_type', 'title', 'rating'
quest_movies = movies[movies['story_type'] == 'Quest']
highest_rated_quest = quest_movies.loc[quest_movies['rating'].idxmax()]
print("Highest rated Quest movie:", highest_rated_quest['title'])

# Assuming column name is 'genre'
most_common_genre = movies['genre'].value_counts().idxmax()
print("Most released genre:", most_common_genre)

# Assuming column 'budget' and 'title'
top5_budget = movies.sort_values(by='budget', ascending=False).head(5)
print("Top 5 Costliest Movies:\n", top5_budget[['title', 'budget']])

import matplotlib.pyplot as plt

# Assuming columns: 'profitability', 'rotten_tomatoes_rating'
plt.scatter(movies['rotten_tomatoes_rating'], movies['profitability'])
plt.xlabel("Rotten Tomatoes Rating")
plt.ylabel("Net Profitability")
plt.title("Profitability vs Rotten Tomatoes Rating")
plt.grid(True)
plt.show()

import numpy as np

data = {
    'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
    'last_name': ['Miller', 'Jacobson', ".", 'Milner', 'Cooze'],
    'age': [42, 52, 36, 24, 73],
    'preTestScore': [4, 24, 31, np.nan, np.nan],
    'postTestScore': ["25,000", "94,000", 57, 62, 70]
}
df = pd.DataFrame(data)