# -*- coding: utf-8 -*-
"""case study III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_bbG1bQa-tgncP7nSt-e1Vt2GmutpCt
"""

import pandas as pd

# Load dataset
df = pd.read_csv("FyntraCustomerData.csv")

# Preview data
print(df.head())

print(df.info())
print("\nSummary statistics:\n", df.describe())

# Check correlation
correlations = df.corr()
print("\nCorrelations:\n", correlations['Yearly Amount Spent'].sort_values(ascending=False))

import seaborn as sns
import matplotlib.pyplot as plt

# Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Pairplot to check relationships
sns.pairplot(df)
plt.show()

print("Correlation with Yearly Amount Spent:")
print(df[['Time on App', 'Time on Website', 'Yearly Amount Spent']].corr())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

# Define features and target
X = df[['Avg. Session Length', 'Time on App', 'Time on Website', 'Length of Membership']]
y = df['Yearly Amount Spent']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Model training
lm = LinearRegression()
lm.fit(X_train, y_train)

# Predicting
predictions = lm.predict(X_test)

# Metrics
print("MAE:", metrics.mean_absolute_error(y_test, predictions))
print("MSE:", metrics.mean_squared_error(y_test, predictions))
print("RMSE:", metrics.mean_squared_error(y_test, predictions, squared=False))

coeff_df = pd.DataFrame(lm.coef_, X.columns, columns=["Coefficient"])
print("\nFeature Importances:\n", coeff_df)